### ISSUE TITLE
Bond Management Service missing?

### ISSUE THREAD

**Issue by ctron** [embassy-rs/nrf-softdevice#108]
I was trying to restrict who can connect over Bluetooth to a device. To my understanding (and I don't really have much understanding of Bluetooth) I would need to bind the connection. And that is what the "Bond Management Service" is for.

However, I couldn't find anything related to that in `nrf-softdevice`. Is that just missing, or is there another way to deal with this?

**Comment by alexmoon** [comment]
Added in #109
