### ISSUE TITLE
Support passing attribute to fields in nrf-softdevice macros

### ISSUE THREAD

**Issue by xgroleau** [embassy-rs/nrf-softdevice#119]
Allowing to propagate attribute could be helpful in the nrf-softdevice-macro create. This would allow to do conditional compilation or maybe ble documentation directly in the code.

As an example, this code will not compile if `dfu` is not enabled
```
#[nrf_softdevice::gatt_server]
pub struct Server {
    #[cfg(feature = "dfu")]
    pub dfu: DfuService,
}
```

**Comment by alexmoon** [comment]
We've just added a Builder pattern API which you can use instead of the macros to get full control including conditional compilation. You can look at the new `ble_dis_bas_peripheral_builder` example or the proc macro expansion to see how to use the new API.

**Comment by alexmoon** [comment]
The ServiceBuilder is an effective workaround for this issue.
