### ISSUE TITLE
[meta] Maintainers needed!

### ISSUE THREAD

**Issue by Dirbaio** [embassy-rs/nrf-softdevice#121]
There's a few PRs pending since a while ago, and I haven't found time for them. If I haven't by now it's unlikely I will in the future. The issue is I'm not familiar at all with how these advanced Bluetooth features work and how Nordic exposes them in the API, and learning all that requires some time.

I don't want to block progress, so I'd like to **hand over maintainership**.

Being a maintainer means you review PRs and issues, but also that you have *complete authority* to make decisions. This way the project is no longer blocked on me. (Of course, you're still welcome on asking me for input! You don't *have* to, or if you do you can ignore it if you don't agree).

(To clarify; the project is *NOT* currently unmaintained. I'm still invested in it, using it for my company's projects. It's just that due to priorities I can't invest time myself in reviewing the more advanced features people are contributing, but would still love to see them get in!)

cc @lulf @bobmcwhirter @alexmoon

**Comment by lulf** [comment]
Same here, happy to act as co-maintainer, but probably won't be active pushing new development given the "deprecation status" of softdevice from Nordic. Reviewing code is fine.

**Comment by alexmoon** [comment]
I'm happy to be co-maintainer as well. I agree with @lulf about new development, I'm just implementing what I need for my product. Long term I'd like to see a new crate implementing the host side of the HCI interface, which could then use Nordic's new softdevice controller. That will be a significant development project, however.

**Comment by Dirbaio** [comment]
Awesome! @lulf, @bobmcwhirter and @alexmoon are hereby appointed as the new ~~dictators~~ maintainers :) 

Thanks guys! :D
