### ISSUE TITLE
WaitFuture panics if send to other task

### ISSUE THREAD

**Issue by Bergmann89** [embassy-rs/nrf-softdevice#130]
Hey guys,

I have implemented a custom async read trait around the `nrf_softdevice::ble::l2cap::Channel` which stores the future returned by `Channel::rx()`. When I send the object to another task, the `WaitFuture` inside the rx future will panic with the message "waker overflow".

Is there a reason to not simply store the latest waker in the future? If not can we change the WaitFuture implementation to something like the following:

```rust
impl<'a, T: Send> Future for WaitFuture<'a, T> {
    type Output = T;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<T> {
        unsafe {
            cortex_m::interrupt::free(|_| {
                let state = &mut *self.signal.state.get();
                match state {
                    State::None => {
                        *state = State::Waiting(cx.waker().clone());
                        Poll::Pending
                    }
                    State::Waiting(w) if w.will_wake(cx.waker()) => Poll::Pending,
                    State::Waiting(w) => {
                        w.wake();
                        *state = State::Waiting(cx.waker().clone());
                        Poll::Pending
                    },
                    State::Signaled(_) => match mem::replace(state, State::None) {
                        State::Signaled(res) => Poll::Ready(res),
                        _ => unreachable!(),
                    },
                }
            })
        }
    }
}
```

Best regards,
Bergmann89.

**Comment by Dirbaio** [comment]
Yes, "waker overflow" should wake the old waker and replace it, instead of panicking.

**Comment by alexmoon** [comment]
@Dirbaio is there a reason not to use embassy-sync's signal instead of re-implementing it here? It looks to me like the only difference is interrupt::free here vs critical-section in embassy-sync.

**Comment by Dirbaio** [comment]
Not many reasons, no... Only reason is `interrupt::free` is very slightly faster than `critical-section` (and it's fine to disable interrupts if it's for <10us). 

Switching to embassy-sync instead of maintaining a separate copy sounds good to me.
