### ISSUE TITLE
Document `nrf_softdevice::gatt_server` proc macro usage in examples

### ISSUE THREAD

**Issue by a-gavin** [embassy-rs/nrf-softdevice#152]
In the `ble_bas_peripheral.rs`, `ble_bas_peripheral_notify.rs`, and `ble_peripheral_onoff.rs` it isn't immediately evident that the `ServerEvent` enums are generated by applying the `nrf_softdevice::gatt_server` proc macro to the `Server` struct in each. PR incoming.

**Comment by alexmoon** [comment]
Closed by #153
