### ISSUE TITLE
What is the difference between nordic crate

### ISSUE THREAD

**Issue by bauerjj** [embassy-rs/nrf-softdevice#186]
Hi, I'm looking at using this on a nordic chip, however I've also noticed that they provide a crate already at least for the s132. https://crates.io/crates/nrf-softdevice-s132. Does this project have a more full-featured bindings than Nordics?

**Comment by alexmoon** [comment]
That crate provides very low level (unsafe) bindings to the C API. It is a community provided crate, like this one (in fact, created by the same person as this one). `nrf-softdevice` provides a high-level safe interface to the softdevice features. Low-level bindings crates are also included in this repo, which should be essentially identical to that crate but may be more up to date.
