### ISSUE TITLE
Switch examples to use default `gatts_attr_tab_size` ?

### ISSUE THREAD

**Issue by plaes** [embassy-rs/nrf-softdevice#209]
Most (if not all) examples currently set `attr_tab_size` to 32768 bytes, which in some cases pushes softdevice's memory usage over 64k, making them unusable for nrf52832.

[Default value for s132](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.s130.api.v2.0.1/group___b_l_e___g_a_t_t_s___a_t_t_r___t_a_b___s_i_z_e.html) is `0x580 == 1408` bytes (while minimum is 248 bytes), which cuts Softdevice's RAM requirement around ~30k for most cases.

Could we switch to use `BLE_GATTS_ATTR_TAB_SIZE_DEFAULT` or even `BLE_GATTS_ATTR_TAB_SIZE_MIN` instead?
``` diff
-        gatts_attr_tab_size: Some(raw::ble_gatts_cfg_attr_tab_size_t { attr_tab_size: 32768 }),
+        gatts_attr_tab_size: Some(raw::ble_gatts_cfg_attr_tab_size_t {
+            attr_tab_size: raw::BLE_GATTS_ATTR_TAB_SIZE_MIN,
+        }),
```

cc: @lulf (same (copy-paste?) issue for your watchful project) :)

**Comment by lulf** [comment]
@plaes good catch, I think it makes sense for these examples.
