### ISSUE TITLE
Security connection

### ISSUE THREAD

**Issue by AliMoal** [embassy-rs/nrf-softdevice#242]
Hi, I need to know about `with_security` function.
If I use it, it just fills some bytes or Softdevice execute the encryption process??
If Sofdevice does this, how?
Thanks

**Comment by alexmoon** [comment]
`with_security` just sets the attribute flags on the characteristic/descriptor. Setting it to a higher value requires a connection to have established at least that level of security before it is authorized to read/write that characteristic/descriptor.
