### ISSUE TITLE
S340 SoftDevice support (for ANT)

### ISSUE THREAD

**Issue by KireinaHoro** [embassy-rs/nrf-softdevice#257]
I'm looking into using the ANT protocol stack from Nordic/Garmin and can help with adding support for the S340 soft device.  Would it be possible to upstream this support, both legally and for interest of this project?  Thanks in advance.

**Comment by Dirbaio** [comment]
previously discussed in #155

tldr is we can't, because the ANT softdevice, headers, docs etc are not freely redistributable.
