### ISSUE TITLE
Disable Softdevice for sleep

### ISSUE THREAD

**Issue by AliMoal** [embassy-rs/nrf-softdevice#268]
I need to disable softdevice to go to system on mode (using wfi function and rtc2), then wake up from system on and enable it again.
How to do that? Is there any delay function with this purpose?

**Comment by Dirbaio** [comment]
There's no function to disable the softdevice.

Why do you want to do that? if it's to save power, you don't need to. Just stop all connections, stop advertising and stop scanning. Having it enabled doesn't use any power, only radio activity does. If you do no radio activity, you'll get the same WFI sleep current as if you had disabled it.

**Comment by AliMoal** [comment]
Yes sir, I need it for saving power. Ok I'll try it.
