### ISSUE TITLE
Nightly Rust issue: method `read` has an incompatible type for trait

### ISSUE THREAD

**Issue by ninjasource** [embassy-rs/nrf-softdevice#63]
This compiler error is happening in nrf-softdevice/src/flash.rs:105:24
For rustc 1.53.0-nightly (42816d61e 2021-04-24)

It may be worthwhile to put the last known working nightly build in the toolchain file (even if it's commented out)

**Comment by Dirbaio** [comment]
This is because nrf-softdevice works with an older version of embassy. Include the `Cargo.lock` from this repo in your project, it'll ensure the right embassy version is used.

I'm aware of it, was going to update nrf-softdevice soon :)

**Comment by ninjasource** [comment]
Got it, thanks. That fixed it. :)
