### ISSUE TITLE
Use of `cortex_m::interrupt::free` in examples

### ISSUE THREAD

**Issue by Stupremee** [embassy-rs/nrf-softdevice#97]
In the readme you say that you should never use `cortex_m::interrupt::free` because of softdevice. However, in the examples the `alloc-cortex-m` crate is used, which uses `cortex_m::interrupt::free` in their implementation [here](https://github.com/rust-embedded/alloc-cortex-m/blob/6c9060ff803f5ac77b003c2cd7764cc3f1beaed2/src/lib.rs#L67-L80).

**Comment by Dirbaio** [comment]
Oops, nice catch. This is not nice, indeed.

GATT examples can work without alloc as-is. Alloc is only used for managing l2cap buffers, I have a project where I do that with `atomic-pool` instead, it's quite nicer. I should update the examples to that (#69)

**Comment by Stupremee** [comment]
Maybe you could add a section in the readme where you list some common crates that use `cortezx_m::interrupt::free`

**Comment by alexmoon** [comment]
Closed by #69
